<ul class="nav navbar-nav">
    <?php
    foreach ($this->container as $page):
        if( ! $page->isVisible() || !$this->navigation()->accept($page))
        	continue;
        
        if( ! $page->hasPages()): ?>
        <li <?php if($page->isActive()) echo 'class="active"'?>>
            <a href="<?php echo $page->getHref() ?>" <?php echo 'target="'.$page->getTarget().'"'; ?>>
                <?php echo $page->getLabel(); ?>
            </a>
        </li>
        <?php else: ?>
        <li class="dropdown <?php if($page->isActive(true)) echo ' active"'?>">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <?php echo $page->getLabel(); ?><b class="caret"></b>
            </a>

            <ul class="dropdown-menu scrollable-menu">
            <?php foreach($page->getPages() as $child): 
            	if( ! $child->isVisible() || !$this->navigation()->accept($child))
            		continue; ?>
                <?php if($child->getLabel()=='Divider'): ?>
                	<li class="divider"></li>
                <?php else :?>
	                <li>
	                    <a href="<?php echo $child->getHref() ?>" <?php echo 'target="'.$child->getTarget().'"'; ?>>
	                        <?php
	                        echo $child->getLabel();
	                        $child_imgs = $child->get('imgs');
	                        if(isset($child_imgs))
	                        foreach ($child_imgs as $img)
	                        	echo $this->imagehelper($img['src'], $img['properties']);
	                        ?>
	                    </a>
	                </li>
                <?php endif;?>
            <?php endforeach; ?>
            </ul>
         </li>   
        <?php endif;
    endforeach; ?>
</ul>