<?php

 $title = 'Countries';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('homeadmin');?>">Back to admin</a>
 </p>
<p>
     <a href="<?php echo $this->url('admincountries', array('action'=>'add'));?>">Add Country</a>
 </p>
 <table class="table">
 <?php foreach ($countries as $country) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($country->name); ?></td>
     <td><?php echo $this->imagehelper('flags/32/'.strtolower($this->escapeHtml($country->iso)).'.png',
     				array('alt_title' => $this->escapeHtml($country->abr), 'height' => '32px'));?></td>
     <td><a href="<?php echo $this->url('admincountries',
             array('action' => 'edit', 'name_url' => $this->escapehtml($country->name_url)));?>">Edit</a></td>
    	<td><a href="<?php echo $this->url('admincountries',
             array('action' => 'delete', 'name_url' => $this->escapehtml($country->name_url)));?>">Delete</a></td>
 </tr>
 <?php endforeach; ?>
 </table>