<?php

 $title = $player->name;
 $this->headTitle($title);
 $action = "lastachieved";
 
 $info_box = "Latest scores in chronological order";
 
 ?>
<?php echo $this->playerheader($action, $player, $platforms);?>
<div class="panel panel-default">
	<div class="panel-heading text-center" title="<?php echo $info_box;?>"><h1>Latest Scores Achieved</h1></div>
 <table class="table table-striped table-hover">
	<?php foreach ($latests as $latest) :?>
	<tr>
	 <?php echo $this->scorehelper($latest, 'lastachieved-player');?>
	</tr>
	<?php endforeach;?>
</table>
<div class="text-center">
 <?php
 echo $this->paginationControl(
     $this->latests,
     'sliding',
     array('partial/paginator.phtml', 'Player'),
     array(
         'route' => 'players',
     	 'params' => array(
		 	'name_url' => $player->name_url,
     		'action' => $action
     	 ),
     )
 );
 ?>
 </div>
</div>