<?php
if(isset($player_1)&&isset($player_2))
	$title = $player_1->name.' VS '.$player_2->name;
else 
	$title = 'VS';
 $this->headTitle($title);
 
 $form->setAttribute('action', $this->url('vs'));
 $form->prepare();
 ?>
 
 <table class="table bordeless">
	 <tr>
	 <td class="col-md-5">
	 <?php if(isset($player_1)) echo $this->vs_header($player_1, $platforms_1);?>
	 </td>
	 <td class="col-md-2 text-center">
	 <?php echo $this->imagehelper('vs.png', array('height' => "200px", 'title' => "Compare your personal records against another Crasher"));?>
	 </td>
	 <td class="col-md-5">
	 <?php if(isset($player_2)) echo $this->vs_header($player_2, $platforms_2);?>
	 </td>
	 </tr>
	<tr>
	 <?php echo $this->form()->openTag($form); ?>
 	<td class="col-md-5 text-center">
	 <?php echo $this->formRow($form->get('player_1'));?>
	 </td>
	 <td class="col-md-2 text-center">
	 <?php echo $this->formSubmit($form->get('submit'));?>
	 </td>
	 <td class="col-md-5 text-center">
	 <?php echo $this->formRow($form->get('player_2'));?>
	 </td>
	 <?php echo $this->form()->closeTag();?>
 	</tr>
 </table>
 
 <?php if(isset($player_1)&&isset($player_2)) :?>
<div class="panel panel-default">
	<div class="panel-heading text-center"><h1>Rankings</h1></div>
	 <table class="table table-striped table-hover h1">
	 	<tr title="Average Position" class="row">
		 	<td class="col-md-5 text-center">
			 <?php echo $player_1->avg_pos;?>
			 </td>
			 <td class="col-md-2 text-center">
			 <?php echo $this->vshelper($player_1->avg_pos, $player_2->avg_pos, true);?>
			 </td>
			 <td class="col-md-5 text-center">
			 <?php echo $player_2->avg_pos;?>
			 </td>
		 </tr>
	 	<tr title="Total" class="row">
		 	<td class="col-md-5 text-center">
			 <?php echo '$'.number_format($player_1->total);?>
			 </td>
			 <td class="col-md-2 text-center">
			 <?php echo $this->vshelper($player_1->total, $player_2->total);?>
			 </td>
			 <td class="col-md-5 text-center">
			 <?php echo '$'.number_format($player_2->total);?>
			 </td>
		 </tr>
	 	<tr title="% WR" class="row">
		 	<td class="col-md-5 text-center">
			 <?php echo $player_1->avg_percent.'%';?>
			 </td>
			 <td class="col-md-2 text-center">
			 <?php echo $this->vshelper($player_1->avg_percent, $player_2->avg_percent);?>
			 </td>
			 <td class="col-md-5 text-center">
			 <?php echo $player_2->avg_percent.'%';?>
			 </td>
		 </tr>
	 	<tr title="Stars" class="row">
		 	<td class="col-md-5 text-center" title="<?php echo $player_1->avg_stars;?>">
			 	<?php echo $this->starhelper($player_1->avg_stars, array('height' => '28px'));?>
			 </td>
			 <td class="col-md-2 text-center">
			 <?php echo $this->vshelper($player_1->avg_stars, $player_2->avg_stars);?>
			 </td>
			 <td class="col-md-5 text-center" title="<?php echo $player_2->avg_stars;?>">
			 	<?php echo $this->starhelper($player_2->avg_stars, array('height' => '28px'));?>
			 </td>
		 </tr>
	</table>
</div>

<div class="panel panel-default">
	<div class="panel-heading text-center"><h1>Personal Records</h1></div>
	 <table class="table table-striped table-hover h1">
	 	<?php
	 	$win_1 = 0;
	 	$win_2 = 0;
	 	foreach ($zones as $zone) : 
	 	$pr_1 = $prs_1->current();
	 	$pr_2 = $prs_2->current();
	 	if ($pr_1 && $pr_1->zone == $zone->id)	{
	 		$score_1 = $pr_1->score;
	 		$rank_1 = $pr_1->chart_rank;
	 		$prs_1->next();
	 	} else {
	 		$score_1 = 0;
	 		$rank_1 = null;
	 	}
	 	if ($pr_2 && $pr_2->zone == $zone->id)	{
	 		$score_2 = $pr_2->score;
	 		$rank_2 = $pr_2->chart_rank;
	 		$prs_2->next();
	 	} else {
	 		$score_2 = 0;
	 		$rank_2 = null;
	 	}
	 	
	 	if($score_1 > $score_2)
	 		$win_1 = $win_1 + 1;
	 	elseif($score_1 < $score_2)
	 		$win_2 = $win_2 + 1;
	 	?>
	 	<tr title="<?php echo $zone->id.' - '.$zone->name; ?>" class="row">
		 	<td class="col-md-1 text-center">
			 <?php $chart_rank = '-';
		    	if ((int)$rank_1 <= 25)
			    	$chart_rank = $this->positionhelper($rank_1, '36px');
			    echo $chart_rank;?>
			 </td>
			 <td class="col-md-4 text-center">
			 <?php echo '$'.number_format($score_1);?>
			 </td>
			 <td class="col-md-2 text-center">
			 <?php echo $this->vshelper($score_1, $score_2);?>
			 </td>
			 <td class="col-md-4 text-center">
			 <?php echo '$'.number_format($score_2);?>
			 </td>
			 <td class="col-md-1 text-center">
			 <?php $chart_rank = '-';
		    	if ((int)$rank_2 <= 25)
			    	$chart_rank = $this->positionhelper($rank_2, '36px');
			    	echo $chart_rank;?>
			 </td>
		 </tr>
		 <?php endforeach;?>
		 <tr title="Total Wins" class="row">
		 	<td class="col-md-1 text-center"></td>
		 	<td class="col-md-4 text-center">
			 <?php echo $win_1?>
			 </td>
			 <td class="col-md-2 text-center">
			 <?php echo $this->vshelper($win_1, $win_2);?>
			 </td>
			 <td class="col-md-4 text-center">
			 <?php echo $win_2;?>
			 </td>
			 <td class="col-md-1 text-center"></td>
		 </tr>
	</table>
</div>
 
 <?php endif;?>