<?php

if(isset($player_1)&&isset($player_2))
	$title = $player_1->name.' VS '.$player_2->name;
else 
	$title = 'VS';
 $this->headTitle($title);
 
 $form->setAttribute('action', $this->url('vs'));
 $form->prepare();
 ?>
 
 <table class="table bordeless">
	 <tr>
	 <td class="col-md-5">
	 <?php if(isset($player_1)) echo $this->vs_header($player_1, $platforms_1);?>
	 </td>
	 <td class="col-md-2 text-center">
	 <?php echo $this->imagehelper('vs.png', array('height' => "200px", 'title' => "Compare your personal records against another Crasher"));?>
	 </td>
	 <td class="col-md-5">
	 <?php if(isset($player_2)) echo $this->vs_header($player_2, $platforms_2);?>
	 </td>
	 </tr>
	<tr>
	 <?php echo $this->form()->openTag($form); ?>
 	<td class="col-md-5 text-center">
	 <?php echo $this->formRow($form->get('player_1'));?>
	 </td>
	 <td class="col-md-2 text-center">
	 <?php echo $this->formSubmit($form->get('submit'));?>
	 </td>
	 <td class="col-md-5 text-center">
	 <?php echo $this->formRow($form->get('player_2'));?>
	 </td>
	 <?php echo $this->form()->closeTag();?>
 	</tr>
 </table>