<?php

 $title = 'Edit News';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'adminnews',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 ?>
 <div class="form-group">
 <?php
 echo $this->formRow($form->get('content'));
 ?>
 </div>
 <?php
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();