<?php

 $title = 'News';
 $this->headTitle('Home');
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('homeadmin');?>">Back to admin</a>
 </p>
 <p>
     <a href="<?php echo $this->url('adminnews', array('action'=>'add'));?>">Add News</a>
 </p>
 <table class="table">
 <tr>
     <th>Content</th>
     <th>Date</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($news as $new) : ?>
 <tr>
     <td><?php echo nl2br($new->content);?></td>
     <td><?php echo $this->escapeHtml($new->registration);?></td>
     <td>
         <a href="<?php echo $this->url('adminnews',
             array('action'=>'edit', 'id' => $new->id));?>">Edit</a>
         <a href="<?php echo $this->url('adminnews',
             array('action'=>'delete', 'id' => $new->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>