<?php

 $this->headTitle($title);
 
 $appearances = array();
 $infos = array();
 $total = 0;
 $platforms = array();
 $freqs = array();

 ?>
 
<h1 title="<?php echo $info_playlist;?>"><?php echo $title;?></h1>
 <table class="table table-hover">
 <?php foreach ($vids as $vid) :?>
 <tr>
 	<?php echo $this->scorehelper($vid, $type); ?>
 </tr>
 <?php 
 $total = $total + $vid->score;
 if(isset($appearances[$vid->player_name]))
 	$appearances[$vid->player_name] = $appearances[$vid->player_name] + 1;
 else {
 	$appearances[$vid->player_name] = 1;
 	$infos[$vid->player_name]['url'] = $vid->player_url;
 	$infos[$vid->player_name]['country_name'] = $vid->country_name;
 	$infos[$vid->player_name]['country_iso'] = $vid->country_iso;
 }

	 if(isset($platforms[$vid->platform]))
	 	$platforms[$vid->platform] = $platforms[$vid->platform]+1;
	 else
	 	$platforms[$vid->platform] = 1;
	 	
	 if(isset($freqs[$vid->freq]))
	 	$freqs[$vid->freq] = $freqs[$vid->freq]+1;
	 else if (!is_null($vid->freq))
	 	$freqs[$vid->freq] = 1;
 endforeach; ?>
 </table>
 
 <h1 class="text-center">Total : <?php echo '$'.number_format($total);?></h1>
 
 
<div class="row">
 	<div class="panel panel-default col-md-4">
 	<div class="panel-heading text-center" title="Counts the number of times a player appears in this playlist"><h1>Players Count</h1></div>
 	<table class="table table-condensed table-hover table-striped">
 <?php arsort($appearances);
 foreach ($appearances as $player => $nb) : ?>
 			<tr>
 				<td class="text-center"><?php echo $this->imageHelper('flags/32/'.strtolower($this->escapeHtml($infos[$player]['country_iso'])).'.png', array(
		    				'alt_title' => $this->escapeHtml($infos[$player]['country_name']),
		    				'height' => '32px'));?></td>
     <td><?php echo '<a href="'.$this->url('players',
        			array('name_url' => $infos[$player]['url'])).'">'.$this->escapeHtml($player).'</a>'; ?></td>
     <td class="text-center"><?php echo $nb; ?></td>
 			</tr>
 <?php endforeach;?>
 		</table>
	</div>
 
 <div class="panel panel-default col-md-3 col-md-offset-1">
 	<div class="panel-heading text-center" title="Counts the number of times a platform appears in this playlist"><h1>Platforms Count</h1></div>
 <table class="table table-condensed table-hover table-striped">
 <?php arsort($platforms);
 foreach ($platforms as $platform => $nb) : ?>
 <tr>
 	<td class="text-center"><?php 
	    	echo $this->imageHelper('logos/'.strtolower($platform).'.png', array('alt_title' => $platform, 'height' => '32px'));
	    	?></td>
     <td class="text-center"><?php echo $nb; ?></td>
 </tr>
 <?php endforeach; ?>
 </table>
	</div>
 
 
<div class="panel panel-default col-md-3 col-md-offset-1">
 	<div class="panel-heading text-center" title="Counts the number of times a frequency appears in this playlist"><h1>Freq Count</h1></div>
 <table class="table table-condensed table-hover table-striped">
 <?php arsort($freqs);
 foreach ($freqs as $freq => $nb) : ?>
 <tr>
 	<td class="text-center"><?php 
	    	echo $this->imageHelper('logos/'.strtolower($freq.'_').'.png', array(
		    				'alt_title' => $freq,
		    				'height' => '32px'));
	    	?></td>
     <td class="text-center"><?php echo $nb; ?></td>
 </tr>
 <?php endforeach; ?>
 </table>
	</div>
	</div>