<?php

 $title = 'Admin';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <h2><a href="<?php echo $this->url('admincountries');?>">Countries</a></h2>
 <h2><a href="<?php echo $this->url('adminnews');?>">News</a></h2>
 <h2><a href="<?php echo $this->url('adminplayers');?>">Players</a></h2>
 <h2><a href="<?php echo $this->url('adminzones');?>">Zones</a></h2>
 <h2><a href="<?php echo $this->url('adminscores');?>">Scores</a></h2>
 <h2><a href="<?php echo $this->url('adminstrats');?>">Strats</a></h2>