<?php

 $title = $country->name.' Players';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->imagehelper('flags/64/'.strtolower($this->escapeHtml($country->iso)).'.png',
     				array('alt_title' => $this->escapeHtml($country->abr), 'height' => '64px')).'  '.$this->escapeHtml($title); ?></h1>

<table class="table table-striped table-hover">
 <?php $previous_rank = 0; $tie = 0; $i = 0; foreach ($players as $player) : ?>
<tr>
	<td class="text-center"><?php 
		if ($previous_rank==$player->avg_pos_rank)
			$tie = $tie+1;
		else
			$tie = 0;
		$i = $i + 1;
		$previous_rank = $player->avg_pos_rank;
		echo $this->positionhelper($i-$tie);?></td>
     <td><a href="<?php echo $this->url('players',
             array('name_url' => $this->escapehtml($player->name_url)));?>">
			 <?php echo $this->escapeHtml($player->name); ?></a>
	</td>
	<td><?php echo 'WCR #'.$player->avg_pos_rank;?></td>
 </tr>
 <?php endforeach; ?>
 </table>