<?php

 $title = 'Delete Player';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->error;?>

 <p>Are you sure that you want to delete the following player :
     <?php echo $this->escapeHtml($this->player->name); ?> ?
 </p>
 <?php
 $url = $this->url('adminplayers', array(
     'action' => 'delete',
     'name_url'     => $this->escapehtml($this->player->name_url),
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="name_url" value="<?php echo $this->escapehtml($this->player->name_url); ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>