<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('World Crash Rankings')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('keywords', 'Burnout 2, crash, mode, wcr, rankings, burnout, racing, game, xbox, gc, x-box, gamecube,
            ps2, playstation, criterion, crash mode, high, score, scores, crashes, record, world record, WR, highscore, highscores, world crash rankings')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath() . '/img/favicon.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    	<div class="wrapper">
	        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	            <div class="container">
	                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/banner.png') ?>" alt="World Crash Rankings"/>&nbsp;<?php echo 'World Crash Rankings' ?></a>
						<?php
						
						$this->navigation('navigation')->menu()->setPartial(array('partial/topnav.phtml', 'default'));
						echo $this->navigation('navigation')->menu()
							->setOnlyActiveBranch(false)
							->render()
						
						?>
	            </div>
	        </nav>
	        <div class="container">
				<?php
				// echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0);
	            echo $this->content;
				?>
	            <hr>
	       	</div>
	       	<div class="push"></div>
	    </div>
            <footer class="footer text-center">
            	2014 - Webdesign by Traperac - Special Thanks to <a href="http://vgr-fr.com">VGR admin Magicbart</a> for hosting this website
            	<br/>Credits : flags icons by <a href="www.icondrawer.com">icondrawer</a> - 
            	proofs icons by <a href="http://icons.mysitemyway.com/">icons.mysitemyway</a> - 
            	stars icons by <a href="https://www.iconfinder.com/">iconfinder</a>
            </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
