<?php

 $title = 'Zones';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('homeadmin');?>">Back to admin</a>
 </p>
 <table class="table">
 <?php foreach ($zones as $zone) : ?>
 <tr>
     <td><a href="<?php echo $this->url('zone',
             array('id' => $zone->id));?>">
			 <?php echo $this->escapeHtml($zone->id.' - '.$zone->name); ?></a></td>
	<td><a href="<?php echo $this->url('adminzones',
             array('action'=>'edit', 'id'=>$zone->id));?>">Edit</a>
 </tr>
 <?php endforeach; ?>
 </table>