<?php

 $title = 'Latest Scores Achieved';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <table class="table">
 <?php foreach ($scores as $score) : ?>
 <tr>
     <?php echo $this->scorehelper($score, 'latest-achieved');?>
 </tr>
 <?php endforeach; ?>
 </table>
 
 <div class="text-center">
 <?php
 echo $this->paginationControl(
     $this->scores,
     'sliding',
     array('partial/paginator.phtml', 'Score'),
     array(
         'route' => 'latest-scores',
     	 'params' => array(
     		'action' => 'lastachieved'
     	 ),
     )
 );
 ?>
 </div>